# Override per l'ambiente di produzione.
fullnameOverride: eurotransit-app-prod
sealedSecrets:
  enabled: true
  catalog:
    encryptedData:
      username: "AgBxGdyVy7quVJn8V0Xzh+TkyXGiqGpdo+Kf3DTKbjW0TGehDK1YBt3tgu/j7naiFYeZnAUxFhZKVwb4SvT84FqnPDfqIVIlAGyR6lZyVqhEDeYq9cYFnTqldi9K1sFoXcJxqJbveRxl9aMN6G5c6k5eB/oib3bILr3SaUuDhT6EA/a2ZRLgm06HNf5OOvZgeBOUxwKQuOahRO7FeeZI3Bw/ciLRPx17CqGMp1brrM86iU3CAQy4QzhKNPRo3wmCnITdQXtXd8bX6X1qkcgMoKevjRWH2PHDEfdOojKC/sLD6ShTLBWJ9+49z7Mb0WKCJN38mzT4b1Llj+55BUgaqiMAvMsBI5I81LGxLvNp3UyU4IkCbAOE+3J7G+QJJfY4tkZK1LY1f4nU558Hdsn+TkeIJZpVeyeKhPDFpiMUJSh5FKOzFUrn86Md216giL1FXItyo2oqqwckqBh8zdl9Cnuaygorddb9aqNcgHJoOFHY98vvfwR95y+N909wR7MCdNs44mLzIySRKLgBqbqBJ9ODxs2d3w5rvjuAzNyV69XOuWbEgSD2UZM8koGBF4OBFaeYGyFyZ/cHLHlRakIohQU7LrqLasMjuJyTvnLBhxNSM1FS0wxkjyIuPDZq80fLqQZRYLPpDmuQCUiQOetRQ3kGWYD6zgRqIvS4aFVKfq91aqty3MvSoRRTW5PlbHdfiRbKeBEkIq7y"
      password: "AgAk9pPPnu7vyCNKj1JFZ6mzSjSOdJcI2wEYu6xjwVh1j+sNNgR0ps1alWCmlTI805STi6ooz8bhvYXWAylm5Z4/79VFAfyYPznoy2c8jMBScO++3Le3Ft9w1llaDED0bDL+jJliqk9ZkBrFJqcFg3BEGiYOtvmXu7PYBGQpnYdfGfRhTLNrsW0OjdxytocZGhJztnopAS5pBL5067PxadqHfrOVTgM4vlbdNXVh95GaI8pdsXniwZREpNsSvBRe8qjT7qdcoygREEyCcZL55Acr4u4VLjkX+sUlOD6r0tpUsJN0nmyS4Ro/9iuqCLj5ym2xQNxLxGrwGDrvl8t42BTdlmxDOfvvMnp/Ft9v67P0uxTKEJOTKhqpKpkYN8ZwcqAZ1N7Q86AXnIFViVgZmQVYJCA8Hl93FT9yshwwmAOXrlsVrtzB14tmYFw8RkaagrTdyWWuw/KwS34us7859p5dCoNAZeq+g3+k9Vy0rZugcmrxkW/D38R5VuL7EnuE7EqYcYLKaY26b1zxNfXZqzPigN4aUYUXRp77vz71SG0QdoOaBBRxf7hlbVqRWysq7m4pXcSMEw9e72OS88XqAnS0fJ/dye9SPEBqDkKj+9BZCYL9TvcVider4Wr+865RaB1CzZv9qPKaKxzKeVW7GZwpmN6BDsuUezQAZeUvOL/Dwqqxh61oVgAsz7nLdQC7sMEaMhZuddrh"
  inventory:
    encryptedData:
      username: "AgCOi487T2NxM6iuG4sovFHRcthCvWONZc8CgK3RpLn6ByxcQDkGRTPPlNTh1d1qqGtasLzCXzi+0LYN79WlvR+BQf2XKEEgb6+ML6ruFY3+MEanohh5PY88J9z6H9HPNaJvdJvNra95dxPHMMU+3c0/Flteqde+7OudIeonJ0gvFe64EpwZeGy8dHqU5Xw9bfXn2CVESLivKiNAmY97sMIpwYQz48+ZwNIXGmP4cBi5KkWj42B9XbiwevngP0s9vkITBEuduGKWgCdKVlfL2a4TYvFYllVMIzdk+TF8QL0HcJm5ddh+PM2yDGX4l3PU1LVeED3MGxbtlnZ4Sbp+YW73thKCfM8sdaJr5qwPg+AyfypPMI3ZTpSS3suc/0zgQJmfmVCmVvq3Yezb7E7GWbKAwZMS/u17Tr8D9LO6cBM5NzUxkuRTZfpUSEtQdOSjxJ74c9K0olAcGYKs6IPO129uv5cBw4Dpzwzr1Vn/bJzxFmYXZIGePtVCOdCGVH5dpRPoprb+ix0xgZwf7dBvO40SmigjhLauAB4BSWNoVUx+iuzjGlANVD6PQOEeh5zzH7WRg8DQuTNEos3JZWIaVSMmKNhtQ59dVOXgO/Sy6SuUoJRqJTj26Ri6nEsuthORcISbRcZk0/9Mq3NUlSe0PxWyi7QPbazzX4taYKB0crZgkogXYuLq3O3YNLahdX8sFAvDEunnvI1JyIc="
      password: "AgB3vCRErclEZ+zqRcHAL8KbAD2oxnrbJHaCpxtQ412bk7/2Qj+HN4XMMdMEmmuFB5znGNNswGfssU+Uq1eJMUe6ipmKB8texQbsYDbf+p2cnbyTCbgM65yKFAOtQzr+vGhUbMY2ihd9v5WdkswXTg0AU3e/cAvB8BjvWjS4OUQfB8tZOAalrfGhRU4JjFvibzaVB5d2FcN3BWJILkipX2t3ceg1RtPDzTpAIIyFJzvM7qUDZ+lRlVxc40vtciZLSAsOyOKdRIstYdGlYvH6cnyDeBvcN/bzA2K9zU2R+F68oOv16tUIMvJsAChiDJGOdkdGtBqTi+V4g44FDON3d00JAqw5op4FPG4VU+8wM6syVABo9oheDLRWpwzowAipx1hBazRR33+7ZuID9XI57hsOCyJFTa3MyKeODvCvic983szcm3z+2XlkOdOQvB+5dt4AKV1xfiafL2Q+LywGlhPJDL6ENImt7ay2cSPhhaPWGIlWSTalJ4uyU+N/9Xmmzz94AHbS4+lrV1EiuaVZLV6s+y6NKRPC4ZjU7/bJeg2IOYttOf8eyM+dyZy+4ZVNNPYor8EH1wKBl9650/g1bgR6OuPA4LH7Vk/6NHnXOCqmWG4jj9RRxRiqPrp0Qk/DqaW2H+TCI4Je5zNSywiPvgsoK9tJFCQKs/pn/ajeDkZwtVcT5MmBiUnRvlOvB9DlWZcaRyTZ84OGbo4NyWmJGX7tyWKlzG77"
  order:
    encryptedData:
      username: "AgA5w7j/S3VsIRJKSuK0AagzGoPOLJGHyPHt8Bu/5GQfLisiFFDCimT+sLjIZOyhXPzNCcHbjPPBtF7zqNR3SlJIFJ3d5fuInqKW7LquxA7hRLZMGtEVqUDA6GXyJRMZVemMZMJ99Otd8m8XdfzrWds/ZnwHPXwVJ8WW/tDjM+o7yl/GzoxbLspfvH7Z79Kg5tinnSvj+apEeK3e4zozofpI4AnRRbbNNKmMgKIMOcbfRHsgE7Vy7i06nlALUyhWTOYycwBPNwptkWWo/sRhyV5RMQBEV7apgqnLfJ37o+AcC7YZZ6qCBcH3AI9Xra8eNSfB08npBpjhMgCwCT+m+2of8Z9jsU7Ql8QIGp2eaqaCRF+bCAIaPIjVdm+DXKpst3goCK5hg2hV/ADHHJ6zvOO6RwZNbKoftUXEoxrYe7MeOM/+jA/ey7oNnpciOuqMxo2r8o7f2ViY++TMmChrLPytParz0tffuBAVOcZ9+NsVlPI0k0pZ0lX2PZYYCl5dj1dDT69+wh5cXXu1qYbWc+1JylT5r22FbCo/WHKnfI2glRnNvQXdsqe3qffK0FRwEGnkauBlQgQLvpTMF56AvcNcBCilBn9II+YY4LDtSTVmMOdJR5S/EyTsX/VUWpRzWnWv1DTuQRXfOIuHnWWbTByqSg2+Kx612p9E/2X8c1Aa3zZnlPwxkSNAqVjFb18ZSbUXCBq0ag=="
      password: "AgDF6QAOcDsloi75Oerwgs8uhmHYjycoBlYLn2vJegr97PvLbAuXJak+56GBQGEc9pYI6kqIyABzf3DX9LX9MENtoGFpbjom+X7NsZD26rJ2Oi5Qzb87EDEPEYK6fLhmqaWmzxUEYW99FdrcNWMeqiphpZqIlFa6FeBCRInPjedXth5nClw/pdl9KLjhc5GEmNOhoGxWVsR2WHjTAFnDjRV6KJs9JT4tQhXeXX/tpF0vp2vaT8GjrthMR42WbcL5EKhIjGMy3NRCZOT0OS6DYdTwnQ/5oZ5sUEJNL6YkYhf5iNIxFHIUYEyb4BzhPL3NMvNqxu/yCQpxu/VWf5SUjZGVNEJevB6FvFzltr2+OI7bQ8qbYarrDtz+vKM7PH1GLW73Gy67yJDEVL+5uUx+cH24RNe/arP/xWSJSOavWk0X95Y8xpSSMpoe8Yui1HrbUH/0/LuLSHNtx7vUGVrTFT/O+pCr/8ROJEAAyG97eEyW0+RZ2FfT/W53UtQYPZl2mdP9ysJi/KpfNMkJTVyNlmR/JpNfoPowW8ljIYWO9UoAeG/KSCrwQ2He3mdBJ2jjgXFeL31VczArcbJZ7Qn5FgY3OzLyQwTs/gSFzV1cpQ3g0cOmvsyLebeCBrDo1GPrj5sCu3eE7iPGKGLh4ktppDZCdfktnlBZ4Z/q6YiBdx9ABnF+s8cZ0i6/TbUEkgGz3W2pS9jj653L5n4vQTGGjJUnGBTrNqq9FhanXA=="

services:
  frontend:
    replicaCount: 1
    image:
      tag: 1.14.4
      pullPolicy: IfNotPresent
  inventory:
    replicaCount: 1
    image:
      tag: 1.14.5
      pullPolicy: IfNotPresent
    extraEnv:
      - name: CATALOG_BASE_URL
        value: http://eurotransit-app-prod-catalog:8080
      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: eurotransit-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  catalog:
    replicaCount: 1
    image:
      tag: 1.14.3
      pullPolicy: IfNotPresent
  order:
    replicaCount: 1
    image:
      tag: 1.14.5
      pullPolicy: IfNotPresent
    extraEnv:
      - name: INVENTORY_BASE_URL
        value: http://eurotransit-app-prod-inventory:8081
      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: eurotransit-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092

ingress:
  host: eurotransit.local
