# Override per l'ambiente di test.
fullnameOverride: eurotransit-app-test
sealedSecrets:
  enabled: true
  catalog:
    encryptedData:
      username: "AgCzULVEff+Y98mNIfOQhlOwdkT/W8/zhKOyQ2wYMKaCq+GhTDA4Vbh3axuGMHLnIJ5GkkyAFQ1AWiXFjYuS5wAov3Z/vnakH15oaTEQCe25VAWgMGOfk45ME3i2hZ6U1Bohq+ZIaUr8TVWkZm0RpnweWc7cGVKKJcmI1GkY4mjcoHkNb+Ak+DQI7i/nDVxNX8eRV4NOdGTI2CcqmwGSxX4haReEgB0hDOYnM7oZiHNb5eNiuK2U65o6JtSn3ewlS7sROrH8LplRvD0WkCh1sGFjV42vHyCmNzCAEJHmxYYU6FG2vvR9q/U9TW2UFM4uzp9z9FD3rTicb+bvfpzTgaT8lnyircdh8Y3TYXhNZSpu15hz1Lzkf3JZL7cIJIHpA6M3mtBSWjRn69rwPFQpcnwPIED28FRoKkUYX3fw0368dQJrh7SQDv5X+1Bx6Rh8Aw7xwTnPfKDRkJ7gkIA4/WZCob3qQA+J5JytXRm6q6Gz+DPnJlKRA90ZdmQ3vH5r4VyRGCXkvxJ9BZ4+Y2vbHVYtrCBvytubizYr/yjjyVU6TLPa6/QdYaGzAyI1fttpnjKmmWeuMkjW+JkDnIIzRq/j8FxSTsD6WXG3X19E12W7yrfiZmG93pkuhVFxtuRYHJ2FmKPmbCaoXWHdfMrkXvmoatDGzViTr0B93keKyCykfL49nMG6fmo6Bv9DG1k8ACEzeSK+xgDX"
      password: "AgA0q3Z0IICTcIb0oQ0O06VgWAjdddbiM8B0LI7FSCFhWL5IU41v1ZAM4XHwoy/iLyaZZOpFoU2qzUt6TcaUyG9urXK+55DkTj34Jayw1VBsASvKTQhjxPjN7HIXARmK01ukZMi1SQZJuhxIelqD4Mm1OPp1Jkhhs50fF1dOqTBNbGdMXi5KczM/QkLlbM+nKsT9WXiX69lwYw/3pWP/ES3SB1kdHtn4yG/X/y/n2pusOaw+dNclbE05phv1rohHrGG6iW/86RKddSOHDaSo09bxYr59pRjYU58tdzX0NOUwd0LGawLjeOcjrshdLC/MNu/MWWH+qNNFtHBwpb/T74Es2mA3ax7MHqNdt/NlahjO3m6VbPS2SncUS56YjCEH/JHG8cQuwLPlHrQRd7e7iIjVvhhU1ZuglPdWCTL8LeKv7SRKVnYqV7rNUGULlo2CsyrSsfn5UBqhuiT3xkWwYEn1gdw8nO6VFRahXDjdA6HOye2j65fyTcbEbfwN9MPzEdbCPbaOj8N+xHUkqVMOR1Kal6PJ0uztFadPiWpmntt0Ts+kqrkU71SYFpnTkvqzMcN/ihcBiZROxhVcI3WddODF/aUOVnEnwTLq8/QppbN/M1GvrANKRV+viMDwfeQ6LGyDz9PFKU0BZJSmnBDPMDEAbZytDMfLXZTUo+es9/PpMYciCLA4KoAkjC11eafEvgOGx3sWAhDj"
  inventory:
    encryptedData:
      username: "AgCEKlCrHK0oDTDio/qm4LhF7nNoznG6Uhm6VLdsI3NdkruBFtZAmMRv+MMeAdbUrNZK/oTROIW3KqKVhQ3Op0pdarhgCV29JTMJYwYPLdeRC2of7tN79piJKzgvs3yJaAUFeD1i+81g2tJw0JjRBVsXH00E7uq5vDPogeoo0qu5tBqecRES/J06tVSEo+n2oeZs5WzeJ2/HX7WMFqd7qxnz6px4iSVrCcACKYBq51JH+ewXPKJU5IihI+gfPwJxaOYxVsjWOfqz+fINvmXbjiJvasfj6L7lm/xopYLn1VcwEhnztoieI7I0nQggfnpJ5g0fXnU973M5cOgRvv5FVUnnZswlRy+HyN+2hu0utfBeqkTRqBOLI6Ux3fKK1RvIVHDe5w9coKz+6rF7u6hDjKc0Jmhx97ce9ixEylH/b/NPowBSADyEY42cW1YWpFd0ZInyhHDUwaqQxSUxXNG7CSoH91fAcmhLy8f1PsM6j8+KPISyHwQZszkaXesNnTH7mhHgT4U1skLmY9KE2E7Z+ReSBRy+IRiJMoFxmyuVLRnbcD8UH3iZi2tmgGah5iCsvU5mVdxR0renXkZoleyftYKc0m6Nc62YfxVmg/gUIM9fhYqQlKpK3wA3XREXeLSKSFMllx0uYufp2Cm62G517jwiv+2JbPDpMqzZSTvUlI5JKd22wazk6/jh8e19apK6S7H5F8DxnxHeb+I="
      password: "AgCeBSYn/c1hH/VM8iupuSqlD4SL9W5pqS59F8OVZMc/iG0BcP+HQ2/PdLM444pqYh7Wb4t/N67s751A238xFODRsJKkuCzpVrx9zkAhbP3fOKz2yBm53K8nUxMUnG4mm2JLMYCnPkqMR9eqlv5uVq41zJGz5VRtsN9+VnzE09aQc3nM6uE8OYjjTlx+vQ9PfQ99THh2ZhpP6qOIUeMYB1tuZRQ1Scl7EHiqNO0E5pEm33NZAmm7wOYaNUOiRC8QhgADWRCuQj3q/3Rt58RUHFCLufvINhjWuI5i81y3qcBS9ryNygWIixZKWuM1M5KRImSonazVF2mOkOv8klIeoHGTYY3/f9aVttppURzTxngjmksIegRoyuYW21AkIHI4+19t5HeqoC2T4GoyL5oGanqAsAhsOJp6JUkaAoUMr81eNkDOg4aCH9uF/J3hQOFhhaxG3oryqAk4nvd9lA2OlMDHZkWmwycLx64x3mmrNWUHphJIqhpjnA/bJ75tVHUIVu7hQ9qadvg9BhTRm+H0nT+TsUpo1d/WSr8iwNiuqKj4Xh4+djXVOSmx8zSZGgxO7e4gv9UIl00Mm66VQCnooSyx8V8vK2/TR77h7WM55MZCsk3gpPn6u9CParwHolv3kfuMp8CATXv6AvD9+ENOoGf+256Tg4uEzqQv5ztokqUZtH9LjGKotuvYfoOCIvktKkctufRyVLrxzsjAe024Y7SPFDu4or/f"
  order:
    encryptedData:
      username: "AgBssv1KaEKwnLlJ5EI+hpoTcMak9+idnhV1aO4+NPwMF3fWM+iCDsW4k8WZsLdE777AjJWM4xTKhBXG6N19eDhVm4/Yy+Jr4GkuTYybOJ49mXDbEwCdk+MZbWgBjGdqOwR7S9ZEJiGIFRqrU1Vo8EjoBO7k+dZvKQRo6up0Fih253QBwjHuiQtoRNt+jrY7eOU4dsdMhMyPJ36IA/rdT1lk0LpLa958AnmiuwC2NcfwUTCPqcXU87HvgYr3gzF4RdXG0wA6IP27XSB5d0l/t+jzjV6XYBOjc7y0LCdwqTHRp2eTf4FsWTg2u3emVrQkiQnSzHHjh1C8dD4QfcECyDnys2xPOOb1oaG4xO4/bswL+Kw7FqqkWroATkklQ60M2DZVITb6810esidOlpsTFzX7Y7b/zCxlIPqT5PznJUh6njd9iUFzjwLfMglCRgKad7KaSUcmhLx7yn+zMH3cg22xfg4QfoaPNJ5rPZBgbVCDQy3qdRsWLPCC5c+U92ktHb7WoeLOrzNVcID8GEbO7E0jYLuNCUDNCqrm+qFuRajkGXy/OzGvSI83gkX0uSZGmvPVruUJlmSAsnSHAQYhJLKK/dGJtNZ7plBgToZm768+UPrfD0xty/FNpgPi/8V+5cXtXGmtKd4fPz2OnuKct8UFWfIUob/jAe/JHLj1+lwiOILsxHDymSDFzn852rqwtlF/bUqzyw=="
      password: "AgAzdVmPf7z6oOudAwiv8z6PiBJ9xvrMP9P/qleKnVHtha5Nt+/IvCrEu5z3I6FW34EmVp/46h5jhJPI8gIHvS2W7wpB2If/pjpRG2LE5LjEcQFhd8KI8lN1ZAfiusV9Rr9lwm3lqk+IWpofk09NQONNDjdzoR5WLaVSdrRLjf6Id0lN9pHWi8EsY7BIvDQ8csfIYt7bE6hd/XPWZdXbzoD2bPKuU9GsFSWcFOMkgOaZRwhb2QYxClQJBndBhlAIVtFcWU2y7cHIbszydfQZ+2EvUSVsbFldz/Dw5UcK2ULfiGCz93bI3/KnDL9f9DLu1SV3p4Ng3yF7lg7Lbq1hkJWayfUHZQBYExTV/6NjgK/u1RVYrw2309XFLE58NasYRJ9HstVYaTPXBXURcwdC+TlMsO6wHnhRoCFpXueJGh5OT2XaTJo63/uc0kxspsewxoGxJntAO9LZLcHaGmh+4vZUFjW0zKfxVGfzeo5fPU6iOaV0OKpXHQta/3jGXq16G5mcp8iySXleIlb4pT14TPrOGYSURN3s26LH8ddcO/wB7VA1xewu71W+dW754gwQfLfyTRwNGVUqLq2Eb53HhxqjLVkc8YoHvu1cn3jyIKkp4OkP2Mt14hZGK+NO1PH+nHXxF+WauO+gCL+3uy6z59jKyITvbemYj/nXuzE8nz4PJvjd3MnEtvat+/n0YIOTAB4qWdbjPleZXQYcWjpxqM1FRgvC4kOKywj7cQ=="
services:
  frontend:
    replicaCount: 1
    image:
      tag: 1.14.7
      pullPolicy: IfNotPresent
      repository: docker.io/lorenzogaetani/eurotransit-frontend
  inventory:
    replicaCount: 1
    image:
      tag: 1.14.8
      pullPolicy: IfNotPresent
      repository: docker.io/lorenzogaetani/eurotransit-inventory
    extraEnv:
      - name: CATALOG_BASE_URL
        value: http://eurotransit-app-test-catalog:8080
      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: eurotransit-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  catalog:
    replicaCount: 1
    image:
      tag: 1.14.6
      pullPolicy: IfNotPresent
      repository: docker.io/lorenzogaetani/eurotransit-catalog
  order:
    replicaCount: 1
    image:
      tag: 1.14.8
      pullPolicy: IfNotPresent
      repository: docker.io/lorenzogaetani/eurotransit-order
    extraEnv:
      - name: INVENTORY_BASE_URL
        value: http://eurotransit-app-test-inventory:8081
      - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: eurotransit-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
ingress:
  host: test.eurotransit.local
