---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eurotransit-app-catalog-db-credentials
  namespace: eurotransit-app
spec:
  encryptedData:
    password: AgBtEQf/FH4jxmhqZ6M+yAhE+6+dxK83k8pMdRI+AxrZWR3ug+BY+yzrrutHMI/tyN3+ImplTSdKnGZ/B6IzxywJCCOf2ngrHeP1daRvX9QyeBH4o5nVpXjrEf6tOJwfJb2AbOdCLjMCpx8NZGDXrl+tBbZvsj44WwuTtb8Mlr9I6Q4KxlcE2QQFDAbYFkh10AvsSBgZZIgWaDi4I0ky1UOYLRMW+ED2BiIZety9AydAntCS/0avd8I+6KjEQN3SJIBM9g4hoyK8y6yRZTmD8WwRZeUzjc/hbPk/Lgr0Ytm/JDx0SR0aeM9xZCwkjwoAuobgGPns8r6aSyDTaXeKPZQTLOmmJhnjjsy9T/fulq421z7KdycKfDvyDDw6MgDn99kOINlZxFLvlpEX26L1HLcgHhpn7jp/IfwxyXQADOEa+qgHmrUX5OrDkSqiW4uTvqVDrlAYGg790KOZ0oTKZASf65osdbb7mbW5gKjkX3iwxkw8pMmWTgGmhjxr3gCpRZrHR3p/Sd0ZecKziX1rnkW9TfWqutpd/Kn2A/Q4Jl8amAvsTKLdZiwzgsFOvIJKIS6mCGhaRLTDyAmsfn2WP8BD8+zROPmVnTPvSBlOLHKUuzPNH0ifiM54o4+wnT8u0f7YHPS0LQBzbN6z3PzBPttw5XUPMPU6YSy8ZHMNaPwlksDGvJsuFA2rL9cHNxojbyt2JUDyZM4A
    username: AgCIbn44qSvyVwp25rVOl5O2sYEEiEYGiyGaaUrpkRAlz99F/s2oi39u+cPELBuF5mzK4kG5shxEw5xpSSH6E8oEGfzQJiRgFD3dmQKIOozDxl8T1qqwtplSfAnTSDI3/kRPugBrdgI1vX7cAUd79fKizQqDbiT4J/wn/PIOra4roA9WIOBl2sdBx/RzoG0Z2bp70NZAIkFbY3fneemKzyD/5p9thyo47E4+cds7E3+BZWNMlGexvKiT6olB8Tl5JrccTf2B8UvaJ+a3ivicLB+m5QO4YGmT7soiIT79msJwK3SSdKle2R5ljk1t+WhupU+9klZm+k0qxulN4L2BpJ4KXnWvOhB4NCJ7Vj2DSi09rs/BoyyABM2kqwFxsilblW27Uy8QtGNaCcCgXDge42UYTs2vNrPMo36kaq3jpGdRPYt65c3bXQd8OQXbLXFFDeR45rTA4q74QPIWZGY2bDND3Ja5I7jRyrscbEjRhHzfjEGvTzPExJyy5Xzg5y+6iM4waBd7Tid59RvdZaguFy5cSJZlAyLDBmfPcSfJ4RSAMi+CgXMBO2DS3U1B52MwJq+mtDpWjm7nFaEy2BusnE29eOa11qAe0Hk2RfTM62StufGJElgDEH2IHdC58NU5O3BoN6BvYDwKjwWXqJC4//QBRVbiDXpteMOvFvn2yR/c4w6JBEVB56O67BPhFOboXAq5YmD/2FSV
  template:
    metadata:
      name: eurotransit-app-catalog-db-credentials
      namespace: eurotransit-app
    type: kubernetes.io/basic-auth
