{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eurotransit-app.fullname" $root }}-{{ $name }}
  labels:
    {{- include "eurotransit-app.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      {{- include "eurotransit-app.selectorLabels" $root | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "eurotransit-app.labels" $root | nindent 8 }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ $svc.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $svc.service.port }}
              protocol: TCP
{{- end }}
{{- end }}
