{{- $secret := .Values.sealedSecrets.inventory -}}
{{- if and .Values.sealedSecrets.enabled $secret.enabled $secret.encryptedData.username $secret.encryptedData.password }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.services.inventory.database.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: {{ $secret.encryptedData.password | quote }}
    username: {{ $secret.encryptedData.username | quote }}
  template:
    metadata:
      name: {{ .Values.services.inventory.database.secretName }}
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/basic-auth
{{- end }}
