---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eurotransit-app-inventory-db-credentials
  namespace: eurotransit-app
spec:
  encryptedData:
    password: AgAgGUHMowaBo4LRRWB7Ej8Yc7p4xi7DtZtoNeGOoFpyKM4fjLwUfT3F+lgXI8sdH6EURCh2LhV6fdMF/z5ZDDzMQVCuDPtsz12CQbPSNU4Qpl5PExIDCkWk7lvFyYOXsIUuJAoDdxzzl/vHufkiJU0S9vyj4Bfijcr2HkeoNGs/6Wzxyn571Bni8UmrUHt4kJVrMFJzZprwA832Efa1RzH2m6N2tDalfmaVsZwDYycERZU/lrf2BTx1Kli6xQiIYJuUPuB5goNncJYT5HoTor/14tx9G0+dGfjVAlkHRymJhUnJt9ABpE8COOf0iuj00eMah2qrCwMfPEGdLeJNIEeRNFqROsnw0YsqoC3lDU9EL/xtb4x9pz1STV1/LtpdsjCrZLBIgX7R37btDLK5yHHtTQQWASZSAj6NU/dYMb4KgHhYOBxdVmYRAxSDZAY4N2N2p8tZfPtGGR+YnRsTvngz8yT/UQvILlXjJL4Awd2e+2foRCCKJOfevuzvlfmpQA0HXV0X+dEX8lc5pQylZPUhgB6V4WXyo14SgT3gZG9+FuXvPqmNqTDkRUWsfBX5AVmfE/mMfEdWrWy6RQjtMfb35eqLfvp7gqC4MN1H+lEZZDw2TegNoKAplsBt+8gl3MZu86s8QzACDgkxjkcTpamkzJmFSmzW2rf0BznOXqqoI571qiXWe8BNaJWGtjrXpP636N/379QNE05rZvGlb4uwXPXCf0lv
    username: AgBhgZUImYdRCab1UaifTDUXdauwXtGRoHee1f9L5tCelRv9m8XNP3Jq964kDmN5eZiIoFImUHLBSlIOukxxjkdEqLflEhEKz3PqEsGYhd8ofnNiAe+o/cEvCAxSEhGR/6FZ78cjZhw6bzK0/db+LL6MAoSY+aaCrWHwXIFrLDJzRVUHj51JizGF5KqHW5ht8H+64CbBWGSpATsNqdEqlPE5AAqI2Zg9WuZsvJv0i4U6EoVoUmCa+XXUK/n+LdDX7bFOqzeZXtQUTdWDnlgSDdcR4ahxbrbz/qjiqhUKjhQrHTmgp2WQbUdfRa9C6aKTPp5FVomtoSJWAW6SuvEl/owSO0PcjoiX4uHUbRDgkMJQOVKFIYwRVqhWrvLQO3MZkyaYahSv8Lpx7xQ8IPRz4YJ36kPJnGz0MHYCo2Gcf5C4oxWBSSFRLX3MYVMC38mcOrCexbsVGRNuZWMFQh/y8tzltFRjHCHxY4eE/SA/mcp2/kHs6zy+otv4geN1cxZa9EpZdo1j3v0TeWbn9MFGHkBXLpZ1fgnUeAjoOvpORFXFEhXdWAFFGn+Lj5MQlCfynooBOzXUVLYuxr8XeCCRgujWW3xXqg/13eSdE/CWqg3vZBaYrHa/l0MYl7zsRFqr8f9NfM0IDNNveMaJtGa092yrYlez6UrTJ6DONPzbXRK8WpDY2AmXYFLqEsDi02cWXyMkduSIEL6Q898=
  template:
    metadata:
      name: eurotransit-app-inventory-db-credentials
      namespace: eurotransit-app
    type: kubernetes.io/basic-auth
