---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eurotransit-app-order-db-credentials
  namespace: eurotransit-app
spec:
  encryptedData:
    password: AgBnw016H9Na4xECd8RZKk58cU7CGm4nPOP4If/l5/DdIcW0g4nbYO3nSKrj8xGPc9st0o2Nd3IF4/5vDsZ3vki6LRrWRyZAqSLlb2gOFGD6Zwpno8jhPqqHKYEfM5rNEnwvIeSOd4XxqBnztkUq3G/HRLxcQxqYaMnI1H0FppWiCqMre0xarnvgJrFCTdorVzB6Wsl6FhSgqrs+JCcBnUSBzN1XcPkf1CV2vkeWZeIZF5tpSEQUOqk+Kv8oBT2n77VrZ0959u+qpa0gChVkox+fr1Ohhq2q9pXhS1sxUqYAipGdQ/5DbdHWS3d4SMrLhmMpUAeFLtfLj9A7k2x/poC68EizF4mvdLC3zxzynRKIv1e1Ef93OQXbvDWTpEduikGDf6LLpazMzutXaLVGXKdiC8ErF4G2Nv1QN5TYrJdstr0vjml/hMh9Ngk9uliYN++0cz9yylYcjFEK78B543VduIzV1PtPlY8mcdhmYySWnjpcu+M/0h1vZ32bZQx45lxUCCiDgfMFmuBKebsY1s5m4QCeBd69UAk5K8SBC/dYwU2dr/oek98m0RDu7ncbKfeJ1Pq5nRdNRS0zlCmqTcZGETb61/789ungvw8Tpx3yWS0RwNXucUSBjfU79moI35W2VVB1/7k35t2TlcDZ61MoIV6B2UdFZdMffqAowBDVJMHy0TE0IIUQRcXOjSAGKPNh/b9IrxNJZPMTCxaYv0FNf5kJUO/TqnNbWA==
    username: AgB3STkG98SR9Wk1wpuaSIE3yAivQ2yiOxqLPdNkHD6BfDrR5HOYIYebOHUxyl4W8/MG48FKNRH8VX/C3k5x0DgnOEQAIccBLcoiAhJK7baeJB+72FTOTUsqTMw16RcOUIbrHgiXcnFEPGPQ4LOPECEb28Qw2uGoinmZD68FLOuiIxvVkBIyl2V+VRRngZuNIMBjW1p8a85WCL3uh8i8bVL4Q0Nezp1oCr/1Xe6mGknHE1jlelVwWya75dzQKyaQ3tlxZeyxPoc/1GHs+zFXw4ce/pWXNFFV+Ws6y3HCL+7SYpKaJX+sD3ga0b8X65z4etG7jFDWJUoBnI1lFRpQ64j+MbiXLZJaD3e4p/nmDSmGYCT08+IMBa8RO08noGMmBcZvjxIdAScBc+bcX7JRWoJ6f7FcnCvec4l8XwBYaAIoijTUzxE0gPjy5aIuvRrveVvYnkTSKS72FR1PV8LRvHxvcIU9olZ0JuUhnu5Vlw0u42QTB+ukzuxJbxu4lPLQ3gBj8UBg+lE1iDXOzfBoG0jVG6eranK+LqmvpUdQr06gCuLdO+RZ+zft9rCeyrnAkGxQQtR3HeHDok7BAxxgkj3sY/1yUJNSUEVoQ9OciJJLjUPN0bN6n3uJVVWSzA3kk5fR9soGfBb1mFWmM8zrhIzfB3dwublhEuzV/tBfNM9ywDhkxEqJE1CggHrssa2qMaXWnSrVOA==
  template:
    metadata:
      name: eurotransit-app-order-db-credentials
      namespace: eurotransit-app
    type: kubernetes.io/basic-auth
