apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eurotransit-app-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LoriGaetani/eurotransit-deploy.git
    targetRevision: master
    path: deploy/charts/eurotransit-app
    helm:
      releaseName: eurotransit-app-test
      valueFiles:
        - values.yaml
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: eurotransit-app-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
